#!/bin/sh
set -e

MY_PATH=$(dirname "$0")
"$MY_PATH/pwnkit-ascii"

# Check for docker

echo "Pulling latest pwnkit image . . ."
sudo docker pull jasperboot/pwnkit:latest
echo "Image pulled succesfully!"

echo "Pulling latest version from GitHub . . ."
git -C "$MY_PATH" pull --no-rebase
echo "Succesfully updated to the latest version!"
