#!/bin/bash

set -e

MY_PATH="`dirname \"$0\"`"
"$MY_PATH/pwnkit-ascii"

# Check for docker

echo "Pulling latest base image . . ."
docker pull jasperboot/kali-full:latest
echo "Base image pulled."

echo "Building docker image . . ."
docker build -t jasperboot/pwnkit:latest --pull .
echo "Docker image built successfully."

echo "Pushing new version to registry . . ."
docker jasperboot/pwnkit:latest
echo "New image pushed succesfully!"
