#!/bin/bash

set -e

MY_PATH="`dirname \"$0\"`"
"$MY_PATH/pwnkit-ascii"

# Check for docker

echo "Pulling latest pwnkit image . . ."
docker pull docker.pkg.github.com/j4sp3r/pwnkit/pwnkit:latest
echo "Image pulled succesfully!"

echo "Pulling latest version from GitHub . . ."
git -C "$MY_PATH" pull
echo "Succesfully updated to the latest version!"
