#!/bin/bash
if [[ "$(docker images docker.pkg.github.com/J4sp3r/pwnkit/pwnkit:latest | grep pwnkit 2> /dev/null)" == "" ]]; then
  echo "Pwnkit is not installed yet. Please run pwnkit-update."
else
  clear
  MY_PATH="`dirname \"$0\"`"
  "$MY_PATH/pwnkit-ascii"
  docker run -i -t --rm docker.pkg.github.com/J4sp3r/pwnkit/pwnkit:latest /bin/bash
fi
