#!/bin/bash

set -e
[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"

MY_PATH="`dirname \"$0\"`"
"$MY_PATH/pwnkit-ascii"

# Check for docker

echo "Pulling latest base image . . ."
sudo docker pull kalilinux/kali-rolling:latest
echo "Base image pulled."

echo "Building docker image . . ."
sudo docker build -t jasperboot/pwnkit:latest --pull .
echo "Docker image built successfully."

echo "Pushing new version to registry . . ."
sudo docker jasperboot/pwnkit:latest
echo "New image pushed succesfully!"
