#!/bin/bash
[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"
if [[ "$(sudo docker images jasperboot/pwnkit:latest | grep pwnkit 2> /dev/null)" == "" ]]; then
  echo "pwnkit is not installed yet."
else
  clear
  MY_PATH="`dirname \"$0\"`"
  "$MY_PATH/pwnkit-ascii"
  INSTANCE=$(sudo docker ps -q)
  sudo docker exec -it $INSTANCE bash -c 'while true; do screen -drqAS gdb-session; sleep 1; done'
fi
