#!/bin/bash

set -e

./ths-ascii

# Check for docker

echo "Pulling latest ths-toolkit image . . ."
docker pull jasperboot/ths-toolkit:latest
echo "Image pulled succesfully!"

echo "Pulling latest version from GitHub . . ."
git pull
echo "Succesfully updated to the latest version!"
