#!/bin/bash

set -e

if [ "$EUID" -ne 0 ]
  then echo "Please run as root."
  exit
fi

./ths-ascii

# Check for docker

echo "Pulling latest ths-toolkit image . . ."
docker pull jasperboot/ths-toolkit:latest
echo "Image pulled succesfully!"

echo "Pulling latest version from GitHub . . ."
git pull
echo "Succesfully updated to the latest version!"
